/**
 * @file Reusable CSV and PDF export buttons for the reports detail view.
 * Uses `react-csv` for CSV downloads and `@react-pdf/renderer` for
 * client-side PDF generation with a table layout.
 */

import { FileSpreadsheet, FileText } from "lucide-react";
import { cn } from "@/lib/utils";
import { CSVLink } from "react-csv";
import {
  PDFDownloadLink,
  Document,
  Page,
  Text,
  View,
  StyleSheet,
} from "@react-pdf/renderer";

// ── PDF Styles ────────────────────────────────────────────────

const pdfStyles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 10,
    fontFamily: "Helvetica",
  },
  header: {
    marginBottom: 24,
    borderBottom: "1px solid #e5e7eb",
    paddingBottom: 12,
  },
  title: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 4,
  },
  subtitle: {
    fontSize: 10,
    color: "#6b7280",
    marginBottom: 2,
  },
  table: {
    marginTop: 8,
  },
  tableHeader: {
    flexDirection: "row",
    borderBottom: "1px solid #d1d5db",
    paddingVertical: 6,
    backgroundColor: "#f9fafb",
  },
  tableRow: {
    flexDirection: "row",
    borderBottom: "1px solid #f3f4f6",
    paddingVertical: 5,
  },
  cell: {
    flex: 1,
    paddingHorizontal: 8,
    fontSize: 9,
  },
  cellRight: {
    flex: 1,
    paddingHorizontal: 8,
    fontSize: 9,
    textAlign: "right",
  },
  footer: {
    marginTop: 24,
    fontSize: 8,
    color: "#9ca3af",
    textAlign: "center",
  },
});

// ── PDF Document Component ────────────────────────────────────

interface ReportPDFProps {
  title: string;
  subtitle: string;
  headers: string[];
  rows: string[][];
  date: string;
}

function ReportPDF({ title, subtitle, headers, rows, date }: ReportPDFProps) {
  return (
    <Document>
      <Page size="A4" style={pdfStyles.page}>
        <View style={pdfStyles.header}>
          <Text style={pdfStyles.title}>{title}</Text>
          <Text style={pdfStyles.subtitle}>{subtitle}</Text>
          <Text style={pdfStyles.subtitle}>Generated: {date}</Text>
        </View>

        <View style={pdfStyles.table}>
          <View style={pdfStyles.tableHeader}>
            {headers.map((h, i) => (
              <Text key={i} style={i === headers.length - 1 ? pdfStyles.cellRight : pdfStyles.cell}>
                {h}
              </Text>
            ))}
          </View>
          {rows.map((row, ri) => (
            <View key={ri} style={pdfStyles.tableRow}>
              {row.map((cell, ci) => (
                <Text key={ci} style={ci === row.length - 1 ? pdfStyles.cellRight : pdfStyles.cell}>
                  {cell}
                </Text>
              ))}
            </View>
          ))}
        </View>

        <Text style={pdfStyles.footer}>
          Report generated by Ecom Dashboard | Data from FakeStore &amp; DummyJSON APIs
        </Text>
      </Page>
    </Document>
  );
}

// ── Column definition for CSV ─────────────────────────────────

interface ExportColumn {
  header: string;
  accessor: (row: Record<string, unknown>) => string | number;
}

// ── Props ─────────────────────────────────────────────────────

/**
 * Props for the {@link ExportButtons} component.
 *
 * @param title   - Report title (used in the PDF header and filenames).
 * @param subtitle - Short description shown below the title in the PDF.
 * @param columns - Column definitions: `header` is the display name, `key` is the
 *                  property name used to access values from each row in `data`.
 * @param data    - Array of flat objects representing the table rows.
 */
export interface ExportButtonsProps {
  title: string;
  subtitle: string;
  columns: { header: string; key: string }[];
  data: Record<string, unknown>[];
}

// ── Component ─────────────────────────────────────────────────

/**
 * Renders CSV and PDF download buttons for a report.
 *
 * - CSV: uses `react-csv`'s `CSVLink` for instant download.
 * - PDF: uses `@react-pdf/renderer`'s `PDFDownloadLink` which generates
 *   the document client-side before triggering the download.
 */
export function ExportButtons({ title, subtitle, columns, data }: ExportButtonsProps) {
  const headers = columns.map((c) => c.header);
  const rows = data.map((row) =>
    columns.map((c) => {
      const val = row[c.key];
      return val == null ? "—" : String(val);
    })
  );
  const date = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const pdfFilename = `${title.replace(/\s+/g, "-").toLowerCase()}-${date.replace(/\s+/g, "-")}.pdf`;
  const csvFilename = `${title.replace(/\s+/g, "-").toLowerCase()}-${date.replace(/\s+/g, "-")}.csv`;

  const csvData = data.map((row) => {
    const obj: Record<string, string | number> = {};
    columns.forEach((c) => {
      const val = row[c.key];
      (obj as Record<string, string | number>)[c.key] = val == null ? "—" : (val as string | number);
    });
    return obj;
  });

  return (
    <div className="flex items-center gap-2">
      {/* CSV Export */}
      <CSVLink
        data={csvData}
        headers={columns.map((c) => ({ label: c.header, key: c.key }))}
        filename={csvFilename}
        className={cn(
          "flex items-center gap-1.5 rounded-lg bg-white dark:bg-zinc-800",
          "px-3 py-2 text-[10px] font-medium text-zinc-600 dark:text-zinc-400",
          "ring-1 ring-zinc-200/60 dark:ring-zinc-700/60",
          "hover:bg-emerald-50 hover:text-emerald-700 hover:ring-emerald-200",
          "dark:hover:bg-emerald-950/30 dark:hover:text-emerald-300 dark:hover:ring-emerald-800/60",
          "transition-all duration-200"
        )}
      >
        <FileSpreadsheet className="h-3.5 w-3.5" />
        CSV
      </CSVLink>

      {/* PDF Export */}
      <PDFDownloadLink
        document={
          <ReportPDF
            title={title}
            subtitle={subtitle}
            headers={headers}
            rows={rows}
            date={date}
          />
        }
        fileName={pdfFilename}
        className={cn(
          "flex items-center gap-1.5 rounded-lg bg-white dark:bg-zinc-800",
          "px-3 py-2 text-[10px] font-medium text-zinc-600 dark:text-zinc-400",
          "ring-1 ring-zinc-200/60 dark:ring-zinc-700/60",
          "hover:bg-rose-50 hover:text-rose-700 hover:ring-rose-200",
          "dark:hover:bg-rose-950/30 dark:hover:text-rose-300 dark:hover:ring-rose-800/60",
          "transition-all duration-200"
        )}
      >
        {({ blob, loading }) => (
          <>
            <FileText className={cn("h-3.5 w-3.5", loading && "animate-pulse")} />
            {loading ? "Preparing..." : "PDF"}
          </>
        )}
      </PDFDownloadLink>
    </div>
  );
}
